version: "3.7"

services:
  db:
    image: postgres:10
    container_name: db
    restart: always
    environment: 
      POSTGRES_DB: ${PSQL_DBNAME}
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports: 
      - 5950:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
  
  api:
    build: .
    container_name: api
    restart: always
    env_file: .env
    ports: 
      - 8008:8008
    volumes: 
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on: 
      - db

volumes:
  pgdata:
    driver: local