version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:10
        environment:
          PSQL_HOST: 127.0.0.1
          PSQL_USER: testuser
          PSQL_DBNAME: pettyCash
          PSQL_PASSWORD: test1234
          NODE_ENV: test
          JWT_SECRET: 1321425263645758363475757
      - image: circleci/postgres:10
        environment:
          POSTGRES_DB: pettyCash
          POSTGRES_PASSWORD: test1234
          POSTGRES_USER: testuser

    working_directory: ~/pc-backend
    steps:
      - checkout
      - run:
          name: Setup dependencies
          command: yarn install
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: |
            yarn -v
            yarn test
      - store_artifacts:
          path: coverage
          prefix: coverage

workflows:
  version: 2
  build:
    jobs:
      - build
